In [3]:
# creating numpy/n-darrays
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr6 = np.arange(10) # np.arange(10,20,2)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr7 = np.linspace(10,20,10) # np.linspace(lower range, upper range, jump)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [19]:
arr1.shape

(5,)

In [20]:
arr2.shape

(2, 4)

In [24]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr9.shape

(2, 2, 2)

In [26]:
arr9.ndim

3

In [27]:
arr2.ndim

2

In [28]:
arr1.size

5

In [29]:
arr9.size

8

In [31]:
arr9.itemsize

4

In [32]:
arr9.dtype

dtype('int32')

In [33]:
arr8.dtype

dtype('float64')

In [34]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [35]:
# list vs numpy array
# numpy array is less mempry consuption, faster then lists
lista = range(100)
arr11 = np.arange(100)

In [36]:
import sys

In [37]:
print(sys.getsizeof(87)*len(lista))

2800


In [39]:
print(arr11.itemsize*arr11.size)

400


In [40]:
import time

In [43]:
x=range(100000)
y=range(100000,200000)

start_time = time.time()

c = [(x+y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.020004987716674805


In [44]:
a = np.arange(100000)
b = np.arange(100000, 200000)

start_time = time.time()

c = a+b

print(time.time()-start_time)

0.0019991397857666016


In [4]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr1


array([1, 2, 3, 4, 5])

In [9]:
arr1[2:4]

array([3, 4])

In [10]:
arr1[-1]

5

In [11]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr12[2]

array([ 8,  9, 10, 11])

In [13]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [15]:
arr12[2:4,1:3] #arr12[row:col]

array([[ 9, 10],
       [13, 14]])

In [5]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [6]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
