In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [3]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [4]:
arr1*arr2 #vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [5]:
arr1*2 # schaler multiplication

array([ 2,  4,  6,  8, 10, 12])

In [6]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [7]:
# dot product
arr3  = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [8]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [11]:
arr4.max()

11

In [12]:
arr4.min()

6